CREATE TABLE IF NOT EXISTS users (
   USER_ID INT NOT NULL PRIMARY KEY,
   USERNAME varchar(20) DEFAULT NULL,
   PASSWORD varchar(20) DEFAULT NULL,
   EMAIL varchar(40) DEFAULT NULL
 );

CREATE TABLE IF NOT EXISTS payment (
   PAYMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
   PAYER VARCHAR(20) DEFAULT NULL,
   AMOUNT DECIMAL DEFAULT NULL,
   PAYMENT_DATE TIMESTAMP DEFAULT NULL,
   USER_ID INT DEFAULT NULL,
   CONSTRAINT USERID_FK FOREIGN KEY (USER_ID) REFERENCES users (USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
